/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.schedulemaster;

import mdlaf.MaterialLookAndFeel;
import mdlaf.components.button.MaterialButtonUI;

import javax.swing.*;

public class App {

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel());
            MainFrame frame = new MainFrame();
        } catch (Throwable t) {
            t.printStackTrace();
        }

    }
}
