package com.schedulemaster.app.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class TimeTableForm extends LectureView {
    private JTable timeTable;
    private JPanel panel;

    private static final String[] HEADER = {"", "월", "화", "수", "목", "금"};
    private static final String[][] RAW_DATA = {
            {"1교시", "", "", "", "", ""},
            {"2교시", "", "", "", "", ""},
            {"3교시", "", "", "", "", ""},
            {"4교시", "", "", "", "", ""},
            {"5교시", "", "", "", "", ""},
            {"6교시", "", "", "", "", ""},
            {"7교시", "", "", "", "", ""},
            {"8교시", "", "", "", "", ""},
            {"9교시", "", "", "", "", ""},
            {"10교시", "", "", "", "", ""}
    };

    public TimeTableForm() {

    }

    @Override
    public void updateView() {

    }

    public JPanel getPanel() {
        return panel;
    }

    private void createUIComponents() {
        timeTable = new JTable(RAW_DATA, HEADER);
        timeTable.getTableHeader().setReorderingAllowed(false);
        timeTable.setEnabled(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(timeTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
